/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kamilcieslik_academic_DotProduct */

#ifndef _Included_com_github_kamilcieslik_academic_DotProduct
#define _Included_com_github_kamilcieslik_academic_DotProduct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kamilcieslik_academic_DotProduct
 * Method:    helloNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_kamilcieslik_academic_DotProduct_helloNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
