#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include <com_github_kamilcieslik_academic_DotProduct.h> // generated by javah via maven-native-plugin

JNIEXPORT void JNICALL Java_com_github_kamilcieslik_academic_DotProduct_helloNative
(JNIEnv * env, jobject obj)
{
puts("Hello from C!");
}